### ISSUE TITLE
ZF3

### ISSUE THREAD

**Issue by merlindorin** [zendframework/zend-console#3]
Hi @Maks3w and others ^^
Just to know if there is a channel of communication about zend-console and ZF3
Just want to contribute and add or port new features because zend-console is ... really poor :-1: .

**Comment by gianarb** [comment]
This is the channel to contrib to zend-console :)
We use #zftalk and #zftalk.dev on IRC..

**Comment by merlindorin** [comment]
Ok, so I've to write some issues ^^
By the way, @Maks3w lead this repo ?

**Comment by Maks3w** [comment]
You can talk about your ideas on #zftalk.dev on freenode or open individual issues for to discuss.

**Comment by merlindorin** [comment]
ok, thank you
