### ISSUE TITLE
array_unique is misused in RouteMatcher->parseDefinition(), and does nothing

### ISSUE THREAD

**Issue by TysonAndre** [zendframework/zend-console#43]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-console/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-console/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question.

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

```php
php > $r = new Zend\Console\RouteMatcher\DefaultRouteMatcher('[--foo | --foo]');                     
php > var_export($r);
Zend\Console\RouteMatcher\DefaultRouteMatcher::__set_state(array(
   'parts' => 
  array (
    0 => 
    array (
      'name' => 'unnamedGroupAt1',
      'literal' => false,
      'required' => false,
      'positional' => false,
      'alternatives' => 
      array (
        0 => 'foo',
        1 => 'foo',
      ),
      'hasValue' => false,
    ),
  ),
```
```php
```

### Expected results

`'alternatives'` should have `'foo'` once, at least according to code comments

### Actual results

`'foo'` occurs twice.

----

See http://php.net/manual/en/function.array-unique.php - this does not modify the input

> Takes an input array and returns a new array without duplicate values.

This snippet occurs 4 times in src/RouteMatcher/DefaultRouteMatcher.php  - It probably should be `$options = array_unique($options);` instead.

```php
                // remove dupes
                array_unique($options);
```

This was detected by static analysis, and may be harmless. I'm not sure of the impact of fixing this.

**Comment by weierophinney** [comment]
@TysonAndre Could you submit a PR to fix this, please?
